### PR TITLE
AI added to make computer a little smarter

### PR DESCRIPTION
**Pull request by kmbwollam**
computer has 50% chance to select "best move" which is based on psychology of human choice.

### CODE REVIEW

**Review by daackerman — COMMENTED** [review]
I like this AI, but I was also wondering how this works in the fact that a Human is more likely to change if they lost last round, and they're more likely to stay if they won. Maybe we could add in a variable to keep track of if the human, won, tied or drew.

If they won, then we should be more likely to change to what beat them. 
If they drew, then we should pick a random choice.
If they lost, then we should be more likely to change to what would beat the tool beating us currently.

I think you have the third one coded, which is 50% of the time to change to what would beat the tool beating us currently.

**Comment by daackerman** [comment]
So the AI remembers its last tool and then

**Comment by kmbwollam** [comment]
If you look at the examples I sent in my blurb earlier today, it doesn't
actually matter if the player won or not, the best choice is the same, just
for different reasons. options 1 and 3 above are the same. We could change
the so to pure random in case of a
draw, but I didn't think it made much of a difference.

**Comment by daackerman** [comment]
Ah!! Just had to run the combinations through my head for a sec. You're totally right.

**Pull request merged**
